"""Qualitative cost tier heuristics.

Does NOT produce real dollar estimates — that requires AWS Pricing API
calls and is out of scope for the MVP. Instead, this module maps workload
characteristics to qualitative bands so the LLM output remains honest.

The actual cost_tiers in the response are generated by the LLM using
these bands as guidance; this module provides helper utilities to
construct the relevant prompt context.
"""

from __future__ import annotations

from app.models import NonFunctionals


def cost_context_hint(nfr: NonFunctionals) -> str:
    """Return a cost guidance string to include in the LLM prompt."""
    hints: list[str] = []

    regions = nfr.regions or 1
    if regions >= 3:
        hints.append("Multi-region active-active roughly triples base infrastructure cost.")
    elif regions == 2:
        hints.append("Active-passive multi-region adds ~50-80% to base cost for standby capacity.")

    sla = nfr.sla_percent
    if sla and sla >= 99.99:
        hints.append(
            "99.99% SLA requires redundant NAT gateways, multi-AZ deployments, and "
            "potentially Route 53 health checks — adds meaningfully to monthly cost."
        )

    if nfr.compliance_flags:
        flags = ", ".join(nfr.compliance_flags)
        hints.append(
            f"Compliance requirements ({flags}) may require dedicated HSMs, "
            "additional logging/monitoring infrastructure, and audit tooling."
        )

    if not hints:
        hints.append("Standard single-region, multi-AZ deployment cost profile.")

    return " ".join(hints)
